---
- name: Set Slave01 Bin Name
  win_copy:
    src: '{{ slave01_path }}\appserver.exe'
    dest: '{{ slave01_path }}\appserver_slave01.exe'
    remote_src: yes

- name: Delete Appserver Bin Files
  win_file:
    path: '{{ item }}\appserver.exe'
    state: absent
  loop: '{{ paths }}'