---
- name: Create Slave01 Service
  win_service:
    name: '{{ slave01_name }}'
    path: '{{ slave01_path }}\appserver_slave01.exe'
    state: stopped
    start_mode: manual
    username: '{{ user }}'
    password: '{{ password }}'