---
- name: Set Lockserver Bin Name
  copy:
    src: '{{ lockserver_path }}/appsrvlinux'
    dest: '{{ lockserver_path }}/app_lockserver'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
    mode: '0775'
    remote_src: yes

- name: Set Slave01 Bin Name
  copy:
    src: '{{ slave01_path }}/appsrvlinux'
    dest: '{{ slave01_path }}/app_slave01'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
    mode: '0775'
    remote_src: yes

- name: Set LD_LIBRARY_PATH Variable in .bashrc
  template:
    src: .bashrc.j2
    dest: /home/vagrant/.bashrc
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
    force: yes

- name: Set LD_LIBRARY_PATH Variable .bash_profile
  template:
    src: .bash_profile.j2
    dest: /home/vagrant/.bash_profile
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
    force: yes