---
- name: Set Lockserver appserver.ini
  template:
    src: totvslockserver.ini.j2
    dest: '{{ lockserver_path }}/appserver.ini'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
    mode: '0775'

- name: Set Slave01 appserver.ini
  template:
    src: totvslave01.ini.j2
    dest: '{{ slave01_path }}/appserver.ini'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'
    mode: '0775'